  public RuntimeIOException(Throwable cause) {
    super(cause);
  }

