    /**
     * Asynchronous method that implements signals handling logic. This method
     * invocation is surrounded by the same doTry of {@link TryCatchFinally}
     * that is used to execute workflow. It means that non handled failure
     * inside this method causes workflow execution failure.
     * 
     * @throws Exception
     *             Prefer throwing {@link WorkflowException}.
     * @throws Exception
     */
